package annotations

import (
	"bytes"
	"io"
	"os"
	"sync"
	"testing"
)

type Psuedo struct {

}

func TestProcess(t *testing.T){
	Options()
	*Option.Dir = "testdata/samples"
	*Option.Verbose = false
	*Option.AbortOnError = false
	*Option.OutputToStdOutOnly = true
	origStdOut := os.Stdout
	// Trap stdout
	r, w, err := os.Pipe()
	if err != nil {
		panic("Cant test because pipe can not be created. Error:"+err.Error())
	}
	os.Stdout = w
	revert := func() {
		os.Stdout = origStdOut
	}
	var wg sync.WaitGroup
	outChannel := make(chan string)
	wg.Add(1)
	go func(wg *sync.WaitGroup) {
		var buf bytes.Buffer
		wg.Done()
		io.Copy(&buf, r)
		outChannel <- buf.String()
	}(&wg)
	wg.Wait()
	Process()

	w.Close()
	revert()

	expected := `// Code generated by WishGen. DO NOT EDIT.
// Source: testdata/samples/sample.go
package sample
func (s *SomeStruct)SetAge(v int) {
	s.age = v
}
func (s *SomeStruct)SetName(v string) {
	s.name = v
}
func (s *SomeStruct)GetAge() int {
	return s.age
}
func (s *SomeStruct)GetName() string {
	return s.name
}
func (s *AnotherStruct)SetName(v string) {
	s.name = v
}
`
	actual := <-outChannel
	if expected != actual {
		t.Error("Test failed. Expected and Actual are not same.")
		t.Logf("Expected: [%s]",expected)
		t.Logf("Actual  : [%s]",actual)
		return
	}
}
